plugins {
    id 'java'
}

group = 'ru.mrbedrockpy'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def nettyVersion = project.property("nettyVersion")
dependencies {
    implementation "io.netty:netty-buffer:$nettyVersion"
    implementation "io.netty:netty-handler:$nettyVersion"
    implementation "io.netty:netty-transport:$nettyVersion"
    implementation project(":core")
    implementation project(":transport-netty")
}