plugins {
    id 'java'
}

group = "ru.mrbedrockpy"
version = "1.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation "io.netty:netty-buffer:4.2.12.Final"
    implementation "io.netty:netty-handler:4.2.12.Final"
    implementation "io.netty:netty-transport:4.2.12.Final"
    implementation project(":core")
}

shadowJar {
    configurations = project.configurations.named('runtimeClasspath').map { [it] }
    archiveFileName = "${project.parent.name}-${project.version}.jar"
}